# syntax=docker/dockerfile:1

# The application image. Four stages, so the thing that ships carries the
# server and nothing that built it: no compiler, no dev dependencies, no
# source. Built for linux/amd64, which is what a Hostinger KVM is.
#
# Node 22, matching @types/node and what `next build` is tested against here.
# Alpine, because the runtime is a Node process and a 60 MB base is 60 MB of
# a small VPS's disk.

# ---------------------------------------------------------------------------
# 1 · Dependencies, cached on the lockfile alone
# ---------------------------------------------------------------------------
FROM node:22-alpine AS deps
WORKDIR /app

# sharp ships prebuilt binaries for musl, but node-gyp still wants these if it
# ever has to fall back. Cheap insurance in a stage that never ships.
RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json ./

# npm 11, not the 10.9 that ships with node:22.
#
# npm 10 refuses this lockfile with "Invalid: lock file's ajv@6.15.0 does not
# satisfy ajv@8.20.0" — eslint pins ajv 6, `table` pins ajv 8, and npm 10's ci
# cannot reconcile two versions of the same package at different depths that
# its own install just wrote. npm 11 resolves it. The lockfile in the repo is
# generated by npm 11 for the same reason.
#
# `npm ci`, never `npm install`: the lockfile is the input, and a build that
# quietly resolves a new minor is a build that is not reproducible.
RUN npm install -g npm@11 && npm ci

# ---------------------------------------------------------------------------
# 2 · Build
# ---------------------------------------------------------------------------
FROM node:22-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next inlines every NEXT_PUBLIC_ variable at build time, so it has to be a
# build arg rather than a runtime environment variable — by the time the
# container starts it is far too late. The RIP number used to be one of
# these too; it now lives in `app_settings`, edited from the admin instead of
# redeployed.
ARG NEXT_PUBLIC_WHATSAPP
ARG NEXT_PUBLIC_INSTAGRAM
ENV NEXT_PUBLIC_WHATSAPP=$NEXT_PUBLIC_WHATSAPP \
    NEXT_PUBLIC_INSTAGRAM=$NEXT_PUBLIC_INSTAGRAM

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# No database is reachable during the build, and none is needed: every page
# that reads one is `dynamic = "force-dynamic"`. A placeholder satisfies the
# throw in `src/db/index.ts` at module load; nothing connects.
ENV DATABASE_URL=postgres://build:build@127.0.0.1:5432/build

RUN npm run build

# ---------------------------------------------------------------------------
# 3 · Migrations, as their own image target
# ---------------------------------------------------------------------------
# Migrations run as a separate one-shot container before the web container
# starts, never on boot inside it. Two web replicas racing `drizzle-kit
# migrate` on the same database is how a migration gets applied twice.
FROM node:22-alpine AS migrator
WORKDIR /app
ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY package.json drizzle.config.ts tsconfig.json ./
COPY drizzle ./drizzle
COPY scripts ./scripts
COPY src ./src

CMD ["npx", "drizzle-kit", "migrate"]

# ---------------------------------------------------------------------------
# 4 · Runtime
# ---------------------------------------------------------------------------
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Not root. A remote code execution in a Node process running as root is a
# remote code execution on the host's filesystem mounts.
RUN addgroup -g 1001 -S nodejs && adduser -u 1001 -S nextjs -G nodejs

COPY --from=builder /app/public ./public
# The standalone bundle already contains the traced node_modules and a
# server.js. `static` and `public` are the two things it does not carry.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Uploads are mounted here. Created and owned up front so the volume is not
# root-owned the first time Docker creates it.
RUN mkdir -p /var/lib/tp && chown -R nextjs:nodejs /var/lib/tp
ENV STORAGE_ROOT=/var/lib/tp

USER nextjs
EXPOSE 3000

# Compose owns the healthcheck, so it can be changed without a rebuild.
CMD ["node", "server.js"]
